# Generated by Django 4.1.2 on 2022-10-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discripton",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "guide_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guide.guide",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Имя автора")),
                (
                    "surname",
                    models.CharField(max_length=40, verbose_name="Фамилия автора"),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
                (
                    "date_of_death",
                    models.DateField(blank=True, null=True, verbose_name="Дата смерти"),
                ),
                (
                    "nation",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Страна"
                    ),
                ),
            ],
            bases=("guide.guide",),
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "guide_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guide.guide",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Назание жанра")),
            ],
            bases=("guide.guide",),
        ),
        migrations.CreateModel(
            name="Publishing",
            fields=[
                (
                    "guide_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guide.guide",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="Имя издательства"),
                ),
            ],
            bases=("guide.guide",),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "guide_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guide.guide",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="Название серии"),
                ),
            ],
            bases=("guide.guide",),
        ),
    ]
