# Generated by Django 4.1.2 on 2022-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Имя автора")),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Фамилия автора",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
                (
                    "date_of_death",
                    models.DateField(blank=True, null=True, verbose_name="Дата смерти"),
                ),
                (
                    "nation",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Страна"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Назание жанра")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publishing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="Имя издательства"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="Название серии"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
            ],
        ),
    ]
