# Generated by Django 4.1.2 on 2022-11-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
    ]
