# Generated by Django 4.1.2 on 2022-10-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Binding",
            fields=[
                (
                    "guide_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guide.guide",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Тип переплета")),
            ],
            bases=("guide.guide",),
        ),
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "guide_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guide.guide",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Формат книги")),
            ],
            bases=("guide.guide",),
        ),
        migrations.CreateModel(
            name="Restrictions",
            fields=[
                (
                    "guide_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guide.guide",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, verbose_name="Возрастные ограничения"
                    ),
                ),
            ],
            bases=("guide.guide",),
        ),
        migrations.RenameField(
            model_name="guide",
            old_name="discripton",
            new_name="description",
        ),
    ]
