# Generated by Django 4.1.2 on 2022-10-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="date_of_death",
        ),
    ]
