# Generated by Django 4.1.2 on 2022-12-02 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=17, verbose_name="Номер телефона"),
                ),
                ("country", models.CharField(max_length=25, verbose_name="Страна")),
                ("city", models.CharField(max_length=25, verbose_name="Город")),
                ("index", models.PositiveIntegerField(verbose_name="Индекс")),
                ("adress1", models.CharField(max_length=50, verbose_name="Адрес")),
                (
                    "adress2",
                    models.CharField(
                        blank=True,
                        default="Не указан",
                        max_length=50,
                        null=True,
                        verbose_name="Дополнительный адрес",
                    ),
                ),
                (
                    "information",
                    models.TextField(
                        blank=True, null=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "extend_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extenduser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
