# Generated by Django 4.1.2 on 2022-11-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guide", "0002_alter_genre_description_alter_series_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="uploads/%Y/%m/%d", verbose_name="Обложка книги"
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Цена"
                    ),
                ),
                (
                    "last_change",
                    models.DateField(
                        auto_now=True, verbose_name="Дата последнего изменение карточки"
                    ),
                ),
                (
                    "add_to_catalog",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата добавления в каталог"
                    ),
                ),
                (
                    "quantity_available",
                    models.PositiveSmallIntegerField(
                        verbose_name="Количество в наличии"
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Вес(гр.)"
                    ),
                ),
                (
                    "quantity_of_pages",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество страниц"
                    ),
                ),
                (
                    "binding",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Переплет"
                    ),
                ),
                (
                    "book_format",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Формат"
                    ),
                ),
                (
                    "year_of_publication",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=4,
                        null=True,
                        verbose_name="Год издания",
                    ),
                ),
                (
                    "isbn",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "age_restrictions",
                    models.TextField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Возрастные ограничения",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("5", "5"),
                            ("7", "7"),
                            ("4", "4"),
                            ("1", "1"),
                            ("10", "10"),
                            ("9", "9"),
                            ("3", "3"),
                            ("2", "2"),
                            ("6", "6"),
                            ("8", "8"),
                        ],
                        default="0",
                        max_length=50,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "availability",
                    models.BooleanField(verbose_name="Доступен для заказа"),
                ),
                (
                    "author_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="guide.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "genre_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="guide.genre",
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "publishing_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="guide.publishing",
                        verbose_name="Издательство",
                    ),
                ),
                (
                    "series_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="guide.series",
                        verbose_name="Серия",
                    ),
                ),
            ],
        ),
    ]
