# Generated by Django 4.1.2 on 2022-11-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_genre_description_alter_series_description"),
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_book",
                to="guide.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="genre_book",
                to="guide.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishing_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publishing_book",
                to="guide.publishing",
                verbose_name="Издательство",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.CharField(
                choices=[
                    ("8", "8"),
                    ("3", "3"),
                    ("1", "1"),
                    ("7", "7"),
                    ("9", "9"),
                    ("0", "0"),
                    ("10", "10"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("2", "2"),
                ],
                default="0",
                max_length=50,
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="series_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series_book",
                to="guide.series",
                verbose_name="Серия",
            ),
        ),
    ]
