# Generated by Django 4.1.2 on 2022-12-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0014_alter_book_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.CharField(
                choices=[
                    ("5", "5"),
                    ("7", "7"),
                    ("10", "10"),
                    ("1", "1"),
                    ("6", "6"),
                    ("9", "9"),
                    ("0", "0"),
                    ("3", "3"),
                    ("8", "8"),
                    ("4", "4"),
                    ("2", "2"),
                ],
                default="0",
                max_length=50,
                verbose_name="Рейтинг",
            ),
        ),
    ]
