# Generated by Django 4.1.2 on 2022-12-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_genre_description_alter_series_description"),
        ("book", "0017_alter_book_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author_book",
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.CharField(
                choices=[
                    ("0", "0"),
                    ("4", "4"),
                    ("1", "1"),
                    ("8", "8"),
                    ("2", "2"),
                    ("7", "7"),
                    ("3", "3"),
                    ("5", "5"),
                    ("6", "6"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default="0",
                max_length=50,
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="author_book",
            field=models.ManyToManyField(
                related_name="authorbook", to="guide.author", verbose_name="Автор"
            ),
        ),
    ]
