# Generated by Django 4.1.2 on 2022-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Курс"
                    ),
                ),
                (
                    "last_change",
                    models.DateField(
                        auto_now=True, verbose_name="Дата последнего изменение карточки"
                    ),
                ),
            ],
        ),
    ]
