# Generated by Django 4.1.2 on 2022-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_cart_user_bookincart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=40, verbose_name="статус")),
            ],
        ),
    ]
