# Generated by Django 4.1.2 on 2022-11-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefon_number",
                    models.PositiveIntegerField(verbose_name="номер телефона"),
                ),
                (
                    "email_adress",
                    models.EmailField(max_length=254, verbose_name="email"),
                ),
                ("adress", models.TextField(max_length=200, verbose_name="Адрес")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="дата изменения"),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Дополнительная информация",
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="order.cart",
                        verbose_name="корзина",
                    ),
                ),
                (
                    "status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statuses",
                        to="order.statuses",
                        verbose_name="статус заказа",
                    ),
                ),
            ],
        ),
    ]
