# Generated by Django 4.1.2 on 2022-12-08 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0007_alter_order_cart_alter_order_status"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentToOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        max_length=1000, verbose_name="комментарий к заказу"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_comment_order",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_comment",
                        to="order.order",
                        verbose_name="Комментируемый заказ",
                    ),
                ),
            ],
        ),
    ]
