# Generated by Django 4.1.2 on 2022-12-08 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_commenttoorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commenttobook",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_comment_book",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор комментария",
            ),
        ),
    ]
