# Generated by Django 4.1.2 on 2022-12-08 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0017_alter_book_rating"),
        ("order", "0007_alter_order_cart_alter_order_status"),
        ("comments", "0003_alter_commenttobook_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commenttobook",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="book_comment",
                to="book.book",
                verbose_name="Комментируемая книга",
            ),
        ),
        migrations.AlterField(
            model_name="commenttoorder",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_comment_order",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
        ),
        migrations.AlterField(
            model_name="commenttoorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_comment",
                to="order.order",
                verbose_name="Комментируемый заказ",
            ),
        ),
    ]
